name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem.csproj

    - name: Build
      run: dotnet build AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem/AirportTicketBookingSystem.Tests/AirportTicketBookingSystem.Tests.csproj --no-build --verbosity normal
